apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: air-fleet
spec:
  replicas: 2
  selector:
    matchLabels:
      app: airfleet-backend  # Match the service selector
  template:
    metadata:
      labels:
        app: airfleet-backend
    spec:
      containers:
      - name: backend
        image: starnxinja/airline-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000  # Match the app's port