apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: air-fleet
spec:
  selector:
    app: airfleet-backend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000  # Match the deployment's containerPort
  type: ClusterIP