apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: air-fleet
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000  # Match the deployment's containerPort
  type: ClusterIP