name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker to use Minikube's environment
        shell: powershell
        run: |
          & minikube -p minikube docker-env --shell powershell | Invoke-Expression
          Write-Output "Docker environment set up"

      - name: Verify Docker Environment
        shell: powershell
        run: |
          docker --version
          docker info --format '{{.ServerVersion}}'

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Frontend Docker Image
        shell: powershell
        run: |
          docker build -f airfleet-management/Dockerfile -t starnxinja/airline-frontend:latest .
          docker push starnxinja/airline-frontend:latest

      - name: Build and Push Backend Docker Image
        shell: powershell
        run: |
          docker build -f airfleet-management-backend/Dockerfile -t starnxinja/airline-backend:latest .
          docker push starnxinja/airline-backend:latest

      - name: Deploy to Minikube
        shell: powershell
        run: |
          kubectl apply -f k8s/backend-deployment.yaml 
          kubectl apply -f k8s/backend-service.yaml 
          kubectl apply -f k8s/frontend-deployment.yaml 
          kubectl apply -f k8s/frontend-service.yaml 
          kubectl apply -f k8s/mongo-deployment.yaml 
          kubectl apply -f k8s/mongo-service.yaml 
          kubectl apply -f k8s/mongo-pvc.yaml 